# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql_functions
import config


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.databaseSelection = QtWidgets.QComboBox(self.centralwidget)
        self.databaseSelection.setObjectName("databaseSelection")
        self.databaseSelection.addItem("")
        self.databaseSelection.addItem("")
        self.databaseSelection.addItem("")
        self.verticalLayout_2.addWidget(self.databaseSelection)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadConfigButton = QtWidgets.QPushButton(self.tab)
        self.loadConfigButton.setObjectName("loadConfigButton")

        self.loadConfigButton.clicked.connect(self.load_config)

        self.verticalLayout.addWidget(self.loadConfigButton)
        self.connectButton = QtWidgets.QPushButton(self.tab)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.databaseNameInput = QtWidgets.QLineEdit(self.tab_3)
        self.databaseNameInput.setObjectName("databaseNameInput")
        self.horizontalLayout_2.addWidget(self.databaseNameInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.createDatabaseButton = QtWidgets.QPushButton(self.tab_3)
        self.createDatabaseButton.setObjectName("createDatabaseButton")

        self.createDatabaseButton.clicked.connect(self.create_database)

        self.verticalLayout_5.addWidget(self.createDatabaseButton)
        self.deleteSelectedDatabaseButton = QtWidgets.QPushButton(self.tab_3)
        self.deleteSelectedDatabaseButton.setObjectName("deleteSelectedDatabaseButton")

        self.deleteSelectedDatabaseButton.clicked.connect(self.delete_selected_db)

        self.verticalLayout_5.addWidget(self.deleteSelectedDatabaseButton)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.databaseSelectionData = QtWidgets.QComboBox(self.tab_2)
        self.databaseSelectionData.setObjectName("databaseSelectionData")
        self.horizontalLayout_3.addWidget(self.databaseSelectionData)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.collectionSelectionData = QtWidgets.QComboBox(self.tab_2)
        self.collectionSelectionData.setObjectName("collectionSelectionData")
        self.horizontalLayout_3.addWidget(self.collectionSelectionData)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.insertButton = QtWidgets.QPushButton(self.tab_2)
        self.insertButton.setObjectName("insertButton")
        self.horizontalLayout_6.addWidget(self.insertButton)
        self.updateSelectedButton = QtWidgets.QPushButton(self.tab_2)
        self.updateSelectedButton.setObjectName("updateSelectedButton")
        self.horizontalLayout_6.addWidget(self.updateSelectedButton)
        self.deleteSelectedButton = QtWidgets.QPushButton(self.tab_2)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.horizontalLayout_6.addWidget(self.deleteSelectedButton)
        self.getAllButton = QtWidgets.QPushButton(self.tab_2)
        self.getAllButton.setObjectName("getAllButton")
        self.horizontalLayout_6.addWidget(self.getAllButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.statusMessage = QtWidgets.QLabel(self.centralwidget)
        self.statusMessage.setText("")
        self.statusMessage.setObjectName("statusMessage")
        self.verticalLayout_2.addWidget(self.statusMessage)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.databaseSelection.setItemText(0, _translate("MainWindow", "MySQL"))
        self.databaseSelection.setItemText(1, _translate("MainWindow", "MongoDB"))
        self.databaseSelection.setItemText(2, _translate("MainWindow", "ArangoDB"))
        self.loadConfigButton.setText(_translate("MainWindow", "Load config"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Enter Database Name:"))
        self.createDatabaseButton.setText(_translate("MainWindow", "Create Database"))
        self.deleteSelectedDatabaseButton.setText(_translate("MainWindow", "Delete Selected Database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Databases"))
        self.label_2.setText(_translate("MainWindow", "Database:"))
        self.label_3.setText(_translate("MainWindow", "Collection:"))
        self.insertButton.setText(_translate("MainWindow", "Insert"))
        self.updateSelectedButton.setText(_translate("MainWindow", "Update Selected"))
        self.deleteSelectedButton.setText(_translate("MainWindow", "Delete Selected"))
        self.getAllButton.setText(_translate("MainWindow", "Get All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data"))

    def db_connect(self, config):
        try:
            mydb = mysql_functions.connection(config["host"], config["user"], config["password"])
            self.statusMessage.setText("There is connection")
            self.set_databases()
            return mydb
        except Exception as e:
            print(e)
            self.statusMessage.setText("Error In connection")

    def create_database(self):
        try:
            db_name = self.databaseNameInput.text()
            mysql_functions.create_database(db_name)
            self.statusMessage.setText("Database {} Created".format(db_name))
            self.set_databases()

        except Exception as e:
            print(e)
            self.message.setText("Database creation failed")

    def load_databases(self):
        columns = ["Database Name"]
        data = [db for db in mysql_functions.show_databases()]
        num_rows = len(data)
        num_cols = len(columns)

        self.tableWidget_2.setRowCount(num_rows)
        self.tableWidget_2.setColumnCount(num_cols)

        self.tableWidget_2.setHorizontalHeaderLabels(columns)

        for row in range(num_rows):
            for column in range(num_cols):
                self.tableWidget_2.setItem(row, column, QtWidgets.QTableWidgetItem((str(data[row][column]))))

    def load_config(self):
        dlg = QtWidgets.QFileDialog()
        dlg.setFileMode(QtWidgets.QFileDialog.ExistingFile)
        mimeTypeFilters = ["application/json"]
        dlg.setMimeTypeFilters(mimeTypeFilters)

        if dlg.exec_():
            filenames = dlg.selectedFiles()
            self.db_connect(config.load_config(filenames[0]))

    def delete_selected_db(self):
        selected_indexes = self.tableWidget_2.selectedIndexes()
        for s in selected_indexes:
            db_name = self.tableWidget_2.itemFromIndex(s).text()
            mysql_functions.drop_database(db_name)
            self.tableWidget_2.removeRow(s.row())
            self.statusMessage.setText("Database {} Deleted".format(db_name))

    def set_databases(self):
        self.databaseSelectionData.addItems([db_name[0] for db_name in mysql_functions.show_databases()])
        self.load_databases()

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
